import type { Metadata } from "next";
import { IBM_Plex_Sans, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster"
import Navbar from "@/components/shared/Navbar";
import { SessionProvider } from "next-auth/react"
import type { AppProps } from "next/app"
import { Provider } from "react-redux";
import { persistor, store } from "@/store/store";
import ReduxProvider from "./StoreProvider";
import Sidebar from "@/components/shared/Sidebar";
// import { PersistGate } from "redux-persist/integration/react";




const IBMPlex = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  variable: '--font-ibm-plex'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={cn("font-IBMPlex antialiased", IBMPlex.variable)}>
        <ReduxProvider>
          {/* <Navbar /> */}
            {children}
            <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
